server:
  port: 8087

spring:
  application:
    name: ebuy-user-service
  datasource:
    url: jdbc:postgresql://ec2-176-34-97-213.eu-west-1.compute.amazonaws.com/dfks70if0oahnb
    username: dvvxxdbaskzhti
    password: 289d658520e0bcead496070aedb9f2e36d51e2bf960b135c5121d53b2f6478c8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  jackson:
    serialization:
      indent_output: true
  kafka:
    bootstrap-servers: rocket-01.srvs.cloudkafka.com:9094,rocket-02.srvs.cloudkafka.com:9094,rocket-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: xha6ilg6-consumers
      auto-offset-reset: latest
    topic:
      userRegistered: xha6ilg6-useregister
      userPassword: xha6ilg6-userpassword
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='xha6ilg6' password='1MA15i4ysm1Rl-Nnwd1SlS2kgDUtFFOt';
        linger:
          ms: 100

eureka:
  client:
    service-url:
      defaultZone: https://ebuy-registry-service.herokuapp.com/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

